# Generated by Django 3.2.12 on 2022-04-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sociedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO SIN RUC (EXPORTACIÓN)')], max_length=1, verbose_name='Tipo de Documento')),
                ('ruc', models.CharField(max_length=15, verbose_name='Ruc')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(max_length=100, verbose_name='Nombre Comercial')),
                ('direccion_legal', models.CharField(max_length=100, verbose_name='Dirección Legal')),
                ('ubigeo', models.CharField(max_length=6, verbose_name='Ubigeo')),
                ('estado_sunat', models.IntegerField(choices=[(1, 'Activo'), (2, 'Baja')], verbose_name='Estado de Empresa según SUNAT')),
            ],
            options={
                'verbose_name': 'Sociedad',
                'verbose_name_plural': 'Sociedades',
            },
        ),
    ]
