# Generated by Django 3.2.12 on 2022-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='img/sociedad', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='ruc',
            field=models.CharField(max_length=15, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='tipo_documento',
            field=models.CharField(choices=[('6', 'RUC - REGISTRO ÚNICO DE CONTRIBUYENTE'), ('1', 'DNI - DOC. NACIONAL DE IDENTIDAD'), ('-', 'VARIOS - VENTAS MENORES A S/.700.00 Y OTROS'), ('4', 'CARNET DE EXTRANJERÍA'), ('7', 'PASAPORTE'), ('A', 'CÉDULA DIPLOMÁTICA DE IDENTIDAD'), ('0', 'NO DOMICILIADO, SIN RUC (EXPORTACIÓN)')], max_length=1, verbose_name='Tipo de Documento'),
        ),
    ]
