# Generated by Django 3.2.12 on 2022-04-12 18:08

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0002_auto_20220412_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociedad',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
