# Generated by Django 3.2.12 on 2022-04-12 20:04

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0004_auto_20220412_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='color',
            field=colorfield.fields.ColorField(default='#FF0000', editable=False, image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Sociedad_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='logo',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='img/sociedad', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sociedad',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Sociedad_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
