# Generated by Django 3.2.12 on 2022-04-18 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sociedad', '0005_auto_20220412_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociedad',
            name='estado_sunat',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'BAJA')], verbose_name='Estado SUNAT'),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=50, verbose_name='Nombre de documento')),
                ('descripcion_docuemnto', models.CharField(max_length=100, verbose_name='Descripción del documento')),
                ('documento', models.CharField(max_length=100, verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Fecha de Modificación')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Documento_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Documento_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
    ]
