# Generated by Django 3.2.12 on 2022-04-18 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0006_auto_20220418_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='sociedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sociedad.sociedad'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='file/sociedad/documento/', verbose_name='Documento'),
        ),
    ]
