# Generated by Django 3.2.12 on 2022-04-18 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0007_auto_20220418_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='descripcion_docuemnto',
            new_name='descripcion_documento',
        ),
    ]
