# Generated by Django 3.2.12 on 2022-04-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociedad', '0009_representantelegal_tiporepresentantelegal'),
    ]

    operations = [
        migrations.AddField(
            model_name='representantelegal',
            name='estado',
            field=models.IntegerField(choices=[(1, 'ACTIVO'), (2, 'BAJA')], default='1', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='representantelegal',
            name='fecha_baja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Baja'),
        ),
    ]
